# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'YTKNetwork', '~> 2.0.4'
target 'testWeChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testWeChat

end
